---
- name: utilize block, rescue and always
  hosts: dbservers
  become: true

  tasks:
    - name: update database

      block:
        - name: display an update message
          debug:
            msg: "updating database"

        - name: update postgresql server to latest version
          yum:
            name: postgresql-server
            state: latest

      rescue:
        - name: display error message that database will be restarted
          debug:
            msg: "update failed. restarting database to correct issues"

        - name: restart database if upgrade failed
          service:
            name: postgresql
            state: restarted

      always:
        - name: notify user of reboot after upgrade attempt
          debug:
            msg: "update process and complete , see previous output for status, rebooting system now"

        - name: reboot system
          reboot:
          
