---
- name: new user is created
  hosts: webservers
  become: true
  vars:
    username: 
      test:
        uname: test
        description: test user account
  
  tasks:
    - name: User
      user:
        name: "{{ username['test']['uname'] }}"
        comment: "{{ username['test']['uname'] }}"
        state: present
