---
- name: new user is created
  hosts: webservers
  become: true
  
  tasks:
    - name: load variables from encrypted file
      include_vars:
        file: ../secret
        
    - name: display the encrypted variables
      debug:
        msg: "{{ secret }}"
      no_log: true
        
    - name: User
      user:
        name: "{{ username['test']['uname'] }}"
        comment: "{{ username['test']['uname'] }}"
        password: "{{ username['test']['password'] }}"
        state: present
