---
- name: new user is created
  hosts: webservers
  become: true
  
  tasks:
    - name: User
      user:
        name: "{{ username['test']['uname'] }}"
        comment: "{{ username['test']['uname'] }}"
        state: present
