---
- name: deploy files using a jinj2 template
  hosts: all
  become: true


  tasks:
    - name: deploy the message of the day template
      template:
        src: ../templates/motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: "0644"

    - name: deploy the hosts file 
      template:
        src: ../templates/hosts.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: "0644"